version: "3.9"

networks:
  mynet:
    name: mynet
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    networks:
      mynet:
        ipv4_address: ${IP_V4_ADDR}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${PORT}:3306
    expose:
      # Opens port 3306 on the container
      - ${PORT}
    # Where our data will be persisted
    volumes:
      - ./mysql_db:/var/lib/mysql
